"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const prisma_1 = require("./src/generated/prisma");
const prisma = new prisma_1.PrismaClient();
async function main() {
    // Supprimer toutes les données existantes
    await prisma.produit.deleteMany({});
    await prisma.produit.createMany({
        data: [
            {
                nom: "Le Produit, C'est Vous",
                slug: "produit-cest-vous",
                sousTitre: "Transformer un parcours professionnel en catalogue de prestations vendables",
                description: "Un parcours en 3 étapes pour 'produitiser' l'expertise des entrepreneurs 50+",
                conceptFondateur: "Problème Central : Les entrepreneurs 50+ peinent à passer de 'vendre mes compétences' à 'commercialiser des produits structurés'. Solution : Un parcours en 3 étapes pour 'produitiser' l'expertise",
                cible: "Entrepreneurs bloqués à 'Je ne sais pas quoi vendre' (Niveau 3), en ligne, par groupes de 8 pp. max",
                problemeResolu: "Je suis coincé dans le piège du temps contre argent. Mes clients ne voient pas ma vraie valeur. Je ne sais pas comment standardiser mon expertise",
                niveauPriorite: 1,
                contenu: "1. Atelier 'Cartographie d'Expertise' (495 €) - Diagnostic : Bilan de compétences, Identification des 'dégoûts/attirances'. Livrables : Carte mentale des savoir-faire exploitables, Grille de priorisation 'Passion vs. Rentabilité vs. Demande', 3 idées de produits pré-packagés. 2. Programme 'Catalogue Clé-en-Main' (1 990 €) - Design produit : Packaging, Argumentaire client, Supports visuels, Relecture par panel de 5 prospects cibles, Modèles de contrats sectoriels. 3. Offre 'Usine à Produits Premium' (4 900 €) - Positionnement : Stratégie de pricing premium (x3 vs. marché), Narrative 'Votre parcours = garantie de résultats', Écosystème complet, Automation",
                processus: "Étape 1 : Cartographie d'Expertise (Jour 1-7) - Audit des compétences exploitables, Session 2 : Packaging 3 offres clés (Jour 7-14), Session 3 : Scripts de vente sectoriels (Jour 14-21), Livraison : Page web vitrine + PDF commercial (Jour 21)",
                duree: "3 mois",
                prix: "495 € / 1 990 € / 4 900 €",
                prixOriginal: null,
                optionsTarification: {
                    cartographie: { prix: 495, nom: "Cartographie d'Expertise", duree: "1 jour" },
                    catalogue: { prix: 1990, nom: "Catalogue Clé-en-Main", duree: "3 semaines" },
                    usine: { prix: 4900, nom: "Usine à Produits Premium", duree: "3 mois" }
                },
                garantie: "Satisfait ou remboursé 30 jours",
                conditionsPaiement: "3x sans frais pour les programmes > 1000€",
                preuves: "Étude interne : 82% des clients augmentent leur CA de +40% en 6 mois",
                temoignages: "Mon catalogue logistique me génère maintenant €15k/mois récurrents",
                resultatsAttendus: "Vendez votre expérience 3x plus cher sans travailler plus, grâce à des offres standardisées et récurrentes",
                differenciation: "Approche : Sur-mesure basé sur votre parcours vs Générique. Livrable : Catalogue opérationnel vs Conseils théoriques. Monétisation : Produits à marge élevée vs Heure facturée. Sectorisation : Intégration métier (logistique, santé, etc.) vs Absente",
                avantagesCompetitifs: "Packaging de l'expertise pour mentorat/co-fondation, Automatisation de la vente des nouveaux produits",
                integrationEcosysteme: "Avec l'Afrique : Packaging de l'expertise pour mentorat/co-fondation. Avec le digital : Automatisation de la vente des nouveaux produits",
                imageHero: "/images/expert-50ans.jpg",
                videoUrl: "/videos/temoignage-pierre.mp4",
                imageProblemes: "/images/problemes-sectoriels.jpg",
                gifSolution: "/images/animation-solution.gif",
                entonnoirNaturel: "Test de profil → '1,2,3 soleil!' → 'Le Produit, C'est Vous'",
                argumentsCommerciaux: "Vendez votre expérience 3x plus cher sans travailler plus, grâce à des offres standardisées et récurrentes",
                urgence: "Offre limitée : 10 sessions/mois max",
                exemplesConcrets: "Ex. pour un ex-directeur logistique : Produit 1 : Audit 'Réduction des coûts stockage', Produit 2 : Formation 'Transition énergétique flotte', Produit 3 : Conseil 'Optimisation douanière Afrique'",
                casPratiques: "ancien pharmacien → 'Directeur Scientifique Indépendant' : Offre signature : 'Validation réglementaire cosmétiques (30j • €15k)', Produit d'appel : 'Quick Scan Formulation' (€990), Prestige : 'Accès annuel à [Sa Marque] Think Tank' (€7k/an)",
                livrable: "Carte mentale des savoir-faire exploitables, Grille de priorisation, 3 idées de produits pré-packagés, Fiches produits, Présentation PDF, Page web dédiée, Modèles de contrats sectoriels, Site web vitrine, Page LinkedIn premium, Témoignages vidéo, Système de booking/paiement intégré, Sequences email pour relance prospects",
                livrablesDetailles: "Carte mentale des savoir-faire exploitables, Grille de priorisation 'Passion vs. Rentabilité vs. Demande', 3 idées de produits pré-packagés, Fiches produits, Présentation PDF, Page web dédiée, Relecture par un panel de 5 prospects cibles, Modèles de contrats sectoriels, Site web vitrine, Page LinkedIn premium, Témoignages vidéo, Système de booking/paiement intégré, Sequences email pour relance prospects",
                supportsInclus: "Templates de contrats sectoriels, Scripts de vente alignés sur les 'pain points' sectoriels, Système de booking/paiement intégré, Sequences email pour relance prospects",
                faq: "Q: Je n'ai pas d'expertise spécifique, ça marche quand même ? R: Oui! 92% de nos clients découvrent 3 compétences monétisables lors de l'audit. Q: Puis-je payer en plusieurs fois ? R: Oui : 3x sans frais pour les programmes > 1000€",
                objectionsAnticipees: "Objection : 'Je n'ai pas assez d'expérience' → Réponse : 'Votre parcours unique est votre plus grande force, pas un handicap'. Objection : 'C'est trop cher' → Réponse : 'Le ROI moyen est de 300% en 6 mois'",
                statut: "actif"
            },
            {
                nom: "Tchiquetchiquetchique AI AI AI !",
                slug: "tchiquetchiquetchique-ai",
                sousTitre: "Kit de survie IA offert pour entrepreneurs 50+",
                description: "Webinaire découverte + outils pour utiliser l'IA dans son business sans tech",
                conceptFondateur: "Problème : Les entrepreneurs 50+ ne maîtrisent pas l'IA et ça les paralyse. Solution : Kit de survie avec prompts magiques et outils gratuits",
                cible: "Tous les entrepreneurs 50+ (surtout Digital Novice)",
                problemeResolu: "Je ne maîtrise pas l'IA et ça me paralyse",
                niveauPriorite: 3,
                contenu: "Webinaire découverte (60 min) : '10 prompts magiques pour : ✓ Rédiger des emails clients, ✓ Analyser la concurrence, ✓ Générer des idées de produits'. Kit survie : Liste des 12 outils IA gratuits, 5 vidéos Loom 'Pas-à-pas', Template : 'Prompt parfait pour votre secteur'",
                processus: "1. Inscription au webinaire gratuit, 2. Participation au webinaire live (60 min), 3. Accès au kit survie complet, 4. Intégration dans la communauté WhatsApp",
                duree: "60 min + accès 90j",
                prix: "Gratuit",
                prixOriginal: null,
                garantie: "100% gratuit, sans engagement",
                conditionsPaiement: "Aucun paiement requis",
                preuves: "De Jean-Marc, ex-commercial : 'J'ai amélioré de 80% ma prospection en 1 mois !'",
                temoignages: "De Jean-Marc, ex-commercial : 'J'ai amélioré de 80% ma prospection en 1 mois !'",
                resultatsAttendus: "Maîtrise des outils IA gratuits, Amélioration de 80% de la prospection, Automatisation des tâches répétitives",
                differenciation: "Gratuit vs formations payantes, Focus entrepreneurs 50+ vs formations génériques, Outils gratuits vs solutions payantes",
                avantagesCompetitifs: "100% gratuit, Spécialement conçu pour les 50+, Outils immédiatement utilisables",
                integrationEcosysteme: "Entrée dans l'entonnoir de vente, Préparation pour les formations payantes",
                entonnoirNaturel: "Première étape de l'entonnoir",
                argumentsCommerciaux: "Découvrez gratuitement comment l'IA peut transformer votre business en 60 minutes",
                urgence: "Webinaires limités à 50 participants",
                exemplesConcrets: "Jean-Marc, ex-commercial : amélioration de 80% de sa prospection en 1 mois grâce aux prompts IA",
                casPratiques: "Utilisation des prompts pour : Rédiger des emails clients, Analyser la concurrence, Générer des idées de produits",
                livrable: "Support webinar, Liste de mes 12 favoris, 10 prompts, 5 Loom, Communauté WhatsApp",
                livrablesDetailles: "Support webinar (60 min), Liste des 12 outils IA gratuits, 5 vidéos Loom 'Pas-à-pas', Template 'Prompt parfait pour votre secteur', PDF téléchargeable, Accès 90j à la communauté WhatsApp",
                supportsInclus: "Liste des 12 outils IA gratuits, 5 vidéos Loom 'Pas-à-pas', Template 'Prompt parfait pour votre secteur'",
                faq: "Q: Dois-je avoir des connaissances techniques ? R: Non, tout est expliqué pas-à-pas. Q: Les outils sont-ils vraiment gratuits ? R: Oui, nous ne recommandons que des outils 100% gratuits",
                objectionsAnticipees: "Objection : 'L'IA va me remplacer' → Réponse : 'L'IA est un outil pour vous faire gagner du temps, pas vous remplacer'. Objection : 'C'est trop compliqué' → Réponse : 'Nous commençons par les bases les plus simples'",
                statut: "actif"
            },
            {
                nom: "1 heure de ping-pong, sans les mains !",
                slug: "1-heure-ping-pong",
                sousTitre: "Audit express de votre projet via questionnaire préalable",
                description: "1 heure de coaching ciblé pour percer 1 blocage stratégique",
                conceptFondateur: "Problème : Besoin d'un avis expert rapide, pas d'un coaching long. Solution : Session express ciblée sur un objectif précis",
                cible: "Opportunistes Agile en phase de test",
                problemeResolu: "J'ai besoin d'un avis expert rapide, pas d'un coaching long",
                niveauPriorite: 1,
                contenu: "Audit express de votre projet via questionnaire préalable, 60 min de coaching ciblé : ✓ Percer 1 blocage stratégique, ✓ Valider 1 hypothèse marché, ✓ Obtenir 1 prochaine action claire",
                processus: "1. Questionnaire préalable (15 min), 2. Session de coaching live (60 min), 3. Livraison des supports",
                duree: "60 min",
                prix: "149 €",
                prixOriginal: null,
                garantie: "Satisfait ou remboursé",
                conditionsPaiement: "Paiement unique",
                preuves: "Résultats immédiats sur un blocage spécifique",
                temoignages: "Clients satisfaits de la rapidité et de l'efficacité",
                resultatsAttendus: "1 blocage stratégique percé, 1 hypothèse marché validée, 1 prochaine action claire définie",
                differenciation: "Session unique ciblée vs programmes longs, Focus sur l'action immédiate vs théorie",
                avantagesCompetitifs: "Rapide, Efficace, Ciblé, Prix accessible",
                integrationEcosysteme: "Première étape avant programmes plus longs",
                entonnoirNaturel: "Test de l'accompagnement",
                argumentsCommerciaux: "Si vous étiez sûr de ne pas vous planter, quelle serait votre prochaine action dans les 72h ?",
                urgence: "Sessions limitées par semaine",
                exemplesConcrets: "Validation d'une hypothèse marché en 60 min, Déblocage d'une situation stratégique",
                casPratiques: "Script Type : 'Si vous étiez sûr de ne pas vous planter, quelle serait votre prochaine action dans les 72h ?'",
                livrable: "Transcription de l'entretien, Enregistrement, Fiche 'Next Step'",
                livrablesDetailles: "Transcription + enregistrement + fiche 'Next Step'",
                supportsInclus: "Questionnaire préalable, Fiche 'Next Step'",
                faq: "Q: Puis-je poser plusieurs questions ? R: Nous nous concentrons sur un objectif principal pour maximiser l'efficacité. Q: La session est-elle enregistrée ? R: Oui, vous recevez l'enregistrement et la transcription",
                objectionsAnticipees: "Objection : 'C'est trop court' → Réponse : '60 minutes ciblées valent mieux que 4h de théorie'. Objection : 'Je préfère un programme complet' → Réponse : 'Cette session peut être le point de départ vers un accompagnement plus long'",
                statut: "actif"
            },
            {
                nom: "1,2,3, soleil !",
                slug: "123-soleil",
                sousTitre: "Validation express de projet avec scénarios financiers",
                description: "Validation express de projet avec scénarios financiers optimiste/pessimiste",
                conceptFondateur: "Problème : Je ne sais pas si mon idée tient financièrement. Solution : Validation rapide avec scénarios financiers",
                cible: "Stratèges Réticents en phase de validation",
                problemeResolu: "Je ne sais pas si mon idée tient financièrement",
                niveauPriorite: 2,
                contenu: "Pré-travail : Questionnaire commercial et financier (20 min), Session Live (2h) : ✓ Estimation du panier moyen et des croissances possibles de clients, des coûts et de la marge, ✓ Scénario optimiste/pessimiste, ✓ Calcul seuil rentabilité, ✓ Identification des 2 risques mortels",
                processus: "1. Questionnaire préalable (20 min), 2. Session live (2h), 3. Livraison des supports",
                duree: "2h",
                prix: "295 €",
                prixOriginal: "495 €",
                garantie: "Satisfait ou remboursé",
                conditionsPaiement: "Paiement unique",
                preuves: "Validation rapide de la viabilité financière",
                temoignages: "Clients ayant évité des projets non viables",
                resultatsAttendus: "Fiche 'Go/No-Go' avec indicateurs clés, Modèle Excel modifiable, Enregistrement personnalisé",
                differenciation: "Validation rapide vs études longues, Focus financier vs conseils généraux",
                avantagesCompetitifs: "Rapide, Financier, Pragmatique",
                integrationEcosysteme: "Étape de validation avant investissement",
                entonnoirNaturel: "Test de profil → 1,2,3 soleil! → Le Produit, C'est Vous",
                argumentsCommerciaux: "Voulez-vous savoir en 2h si votre projet tient financièrement ?",
                urgence: "Offre limitée : 10 sessions/mois max",
                exemplesConcrets: "Validation de projets entrepreneuriaux, Identification de risques financiers",
                casPratiques: "Calcul de seuil de rentabilité, Identification des 2 risques mortels",
                livrable: "2h live, 2 scénarios sur tableur, Fiche décision",
                livrablesDetailles: "Fiche 'Go/No-Go' avec indicateurs clés, Modèle Excel modifiable, Enregistrement personnalisé",
                supportsInclus: "Questionnaire commercial et financier, Modèle Excel modifiable",
                faq: "Q: Avez-vous besoin de mes données financières ? R: Non, nous travaillons avec des estimations basées sur votre secteur. Q: Le modèle Excel est-il personnalisé ? R: Oui, il est adapté à votre projet spécifique",
                objectionsAnticipees: "Objection : 'Je n'ai pas de données financières' → Réponse : 'Nous travaillons avec des estimations sectorielles'. Objection : 'C'est cher pour 2h' → Réponse : 'Cela peut vous éviter des mois de travail sur un projet non viable'",
                statut: "actif"
            },
            {
                nom: "Premiers clients, la preuve par 3+3+3",
                slug: "premiers-clients-3-3-3",
                sousTitre: "Programme 3 semaines : 3 offres structurées, 3 canaux testés, 3 clients",
                description: "Programme 3 semaines pour obtenir ses premiers clients",
                conceptFondateur: "Problème : J'ai structuré mon offre mais aucun client. Solution : Programme structuré pour obtenir 3 premiers clients",
                cible: "Tous profils - phase de commercialisation",
                problemeResolu: "J'ai structuré mon offre mais aucun client",
                niveauPriorite: 2,
                contenu: "Semaine 1 : Packager 3 offres avec Template 'Argumentaire Choc', Semaine 2 : Tester 3 canaux avec Scripts phoning/messaging sectoriels, Semaine 3 : Signer 3 clients avec Checklist closing",
                processus: "Semaine 1 : Packager 3 offres, Semaine 2 : Tester 3 canaux, Semaine 3 : Signer 3 clients",
                duree: "3 semaines",
                prix: "895 €",
                prixOriginal: null,
                garantie: "Remboursé si 0 client après application stricte des méthodes",
                conditionsPaiement: "Paiement unique ou 2x",
                preuves: "Méthode éprouvée pour obtenir les premiers clients",
                temoignages: "Clients ayant obtenu leurs 3 premiers clients en 3 semaines",
                resultatsAttendus: "3 premiers clients signés, Templates & scripts réutilisables",
                differenciation: "Programme structuré vs conseils généraux, Garantie de résultats vs promesses vagues",
                avantagesCompetitifs: "Structuré, Garanti, Pragmatique",
                integrationEcosysteme: "Suite logique après structuration de l'offre",
                entonnoirNaturel: "Après 'Le Produit, C'est Vous'",
                argumentsCommerciaux: "Obtenez vos 3 premiers clients en 3 semaines ou remboursé",
                urgence: "Programme limité à 20 participants par session",
                exemplesConcrets: "Entrepreneurs ayant obtenu leurs 3 premiers clients en 3 semaines",
                casPratiques: "Template 'Argumentaire Choc', Scripts phoning/messaging sectoriels, Checklist closing",
                livrable: "Fiches processus, Scripts, Plan d'action",
                livrablesDetailles: "Templates & scripts, Template 'Argumentaire Choc', Scripts phoning/messaging sectoriels, Checklist closing",
                supportsInclus: "Templates & scripts, Template 'Argumentaire Choc', Scripts phoning/messaging sectoriels, Checklist closing",
                faq: "Q: Que se passe-t-il si je n'obtiens pas 3 clients ? R: Vous êtes remboursé si vous avez appliqué strictement les méthodes. Q: Les templates sont-ils personnalisables ? R: Oui, ils sont adaptés à votre secteur",
                objectionsAnticipees: "Objection : 'Je n'ai pas de réseau' → Réponse : 'Nous vous donnons les méthodes pour créer votre réseau'. Objection : 'C'est trop rapide' → Réponse : '3 semaines c'est le temps optimal pour créer l'urgence'",
                statut: "actif"
            },
            {
                nom: "La mue est enfant de Bohême",
                slug: "la-mue-est-enfant-de-boheme",
                sousTitre: "6 semaines d'accompagnement : Stratégie premium originale",
                description: "Parcours en 6 semaines pour entrepreneurs en réinvention radicale (passion/opportunité)",
                conceptFondateur: "Problème : Je veux lancer un projet aligné avec mes valeurs, pas juste mon CV. Solution : Parcours de transformation de la passion au projet",
                cible: "Entrepreneurs en réinvention radicale (passion/opportunité)",
                problemeResolu: "Je veux lancer un projet aligné avec mes valeurs, pas juste mon CV",
                niveauPriorite: 3,
                contenu: "Séance 1 : 'Éveil' (2h) - Cartographie des passions/convictions, Identification des opportunités. Semaines 1-4 : 'Exploration' (4x30min/sem) - Session 1 : Business model alternatif, Session 2 : Étude concurrence éthique, Session 3 : Prototype rapide, Session 4 : Test marché minimal. Séance 6 : 'Révélation' (1h) - Plan de transition sur 90j, Checklist export (si applicable)",
                processus: "Séance 1 : Éveil (2h), Semaines 1-4 : Exploration (4x30min/sem), Séance 6 : Révélation (1h)",
                duree: "6 semaines",
                prix: "1 495 €",
                prixOriginal: null,
                garantie: "Satisfait ou remboursé 30 jours",
                conditionsPaiement: "Paiement unique ou 2x",
                preuves: "Méthode éprouvée pour la réinvention entrepreneuriale",
                temoignages: "Entrepreneurs ayant trouvé leur nouvelle voie alignée avec leurs valeurs",
                resultatsAttendus: "Plan de transition sur 90j, Checklist export pour projets internationaux",
                differenciation: "Focus valeurs vs profit uniquement, Approche éthique vs business classique, Projets à mission vs projets traditionnels",
                avantagesCompetitifs: "Alignement valeurs/projet, Approche éthique, Projets à mission",
                integrationEcosysteme: "Complémentaire aux autres programmes, Spécialisation valeurs",
                entonnoirNaturel: "Programme spécialisé pour réinvention",
                argumentsCommerciaux: "Transformez votre passion en projet rentable aligné avec vos valeurs",
                urgence: "Programme limité à 10 participants par session",
                exemplesConcrets: "Entrepreneurs ayant transformé leur passion en projet rentable",
                casPratiques: "Étude concurrence éthique, Business model alternatif, Prototype rapide",
                livrable: "Étude concurrence, Argumentaire, Checklist export",
                livrablesDetailles: "Étude concurrence : Analyse des acteurs 'à mission' (ESG, B Corp), Argumentaire : Narratif 'Pourquoi ce projet a du sens' (liant parcours/passion), Checklist export pour projets internationaux : régulations + réseaux militants",
                supportsInclus: "Templates d'étude concurrence éthique, Modèles de business plan alternatif, Checklist export",
                faq: "Q: Dois-je abandonner mon projet actuel ? R: Non, nous explorons des alternatives alignées avec vos valeurs. Q: Les projets éthiques sont-ils rentables ? R: Oui, les consommateurs privilégient de plus en plus les entreprises à mission",
                objectionsAnticipees: "Objection : 'Les projets éthiques ne sont pas rentables' → Réponse : 'Les consommateurs privilégient de plus en plus les entreprises à mission'. Objection : 'Je n'ai pas de passion spécifique' → Réponse : 'Nous vous aidons à identifier vos valeurs profondes'",
                statut: "actif"
            },
            {
                nom: "Audit 720°",
                slug: "audit-720",
                sousTitre: "Audit stratégique en 2 x 2 demi-journées espacées d'une semaine à 10 jours",
                description: "Audit stratégique complet pour entrepreneurs déterminés (CA > 50k€)",
                conceptFondateur: "Problème : J'ai un projet et des idées, mais pas de vision claire. Solution : Audit stratégique approfondi avec focus sur l'actionnable immédiat",
                cible: "Entrepreneurs déterminés (CA > 50k€)",
                problemeResolu: "J'ai un projet et des idées, mais pas de vision claire",
                niveauPriorite: 1,
                contenu: "Jour 1 : Diagnostic stratégique, Pause 7j : Tests terrain, Jour 8 : Plan de bataille 90j. Option webinar par 4 à 6 personnes (1 295 €) : Analyses moins individualisées, Dynamique collaborative",
                processus: "Jour 1 : Diagnostic stratégique, Pause 7j : Tests terrain, Jour 8 : Plan de bataille 90j",
                duree: "2 demi-journées espacées d'une semaine",
                prix: "2 495 €",
                prixOriginal: null,
                optionsTarification: {
                    individuel: { prix: 2495, nom: "Audit 720° Individuel", duree: "2 demi-journées" },
                    webinar: { prix: 1295, nom: "Audit 720° Webinar", duree: "4-6 personnes" }
                },
                garantie: "Satisfait ou remboursé 30 jours",
                conditionsPaiement: "Paiement unique ou 2x",
                preuves: "70% de notre temps sur l'actionnable immédiat vs audits théoriques",
                temoignages: "Entrepreneurs ayant obtenu une vision claire et un plan d'action concret",
                resultatsAttendus: "Verbatim détaillé des 4 séances, Roadmap des priorités",
                differenciation: "Contre les audits théoriques : 70% de notre temps sur l'actionnable immédiat",
                avantagesCompetitifs: "Focus actionnable, Tests terrain, Plan concret",
                integrationEcosysteme: "Complémentaire aux autres programmes, Spécialisation stratégie",
                entonnoirNaturel: "Programme spécialisé pour vision stratégique",
                argumentsCommerciaux: "Obtenez une vision claire et un plan d'action concret en 2 demi-journées",
                urgence: "Audits limités à 5 par mois",
                exemplesConcrets: "Entrepreneurs ayant obtenu une vision claire et un plan d'action",
                casPratiques: "Diagnostic stratégique, Tests terrain, Plan de bataille 90j",
                livrable: "Quick wins, Roadmap, Recommandations sectorielles",
                livrablesDetailles: "Verbatim détaillé des 4 séances, Roadmap des priorités, Recommandations sectorielles",
                supportsInclus: "Templates de diagnostic stratégique, Modèles de roadmap, Recommandations sectorielles",
                faq: "Q: Avez-vous besoin de mes données financières ? R: Oui, pour un diagnostic complet et précis. Q: Les tests terrain sont-ils inclus ? R: Oui, nous vous guidons pour tester vos hypothèses",
                objectionsAnticipees: "Objection : 'C'est cher pour 2 demi-journées' → Réponse : '70% de notre temps est consacré à l'actionnable immédiat'. Objection : 'Je préfère un accompagnement long' → Réponse : 'Cet audit peut être le point de départ d'un accompagnement plus long'",
                statut: "actif"
            },
            {
                nom: "Station-service BP",
                slug: "station-service-bp",
                sousTitre: "Stratégie de projet, Business plan avec tableaux de simulation, pitch-decks clients & investisseur en 10 jours clé-en-mains",
                description: "Business plan complet avec pitch-decks pour entrepreneurs cherchant financement",
                conceptFondateur: "Problème : Mon business plan ne convainc pas les investisseurs. Solution : Business plan complet avec pitch-decks professionnels",
                cible: "Bâtisseurs Visionnaires cherchent financement",
                problemeResolu: "Mon business plan ne convainc pas les investisseurs",
                niveauPriorite: 1,
                contenu: "J1-2 : Modèle financier 3 ans (scénarios + sensibilité), J3-5 : Pitch deck clients ('problème/solution'), J6-8 : Pitch deck investisseurs (ROI + exit strategy), J9-10 : Stratégie financement (subventions → VC)",
                processus: "J1-2 : Modèle financier, J3-5 : Pitch deck clients, J6-8 : Pitch deck investisseurs, J9-10 : Stratégie financement",
                duree: "10 jours",
                prix: "3 900 €",
                prixOriginal: null,
                garantie: "Satisfait ou remboursé 30 jours",
                conditionsPaiement: "Paiement unique ou 3x",
                preuves: "Business plans ayant obtenu des financements",
                temoignages: "Entrepreneurs ayant obtenu des financements grâce à nos business plans",
                resultatsAttendus: "2 pitch decks 'prêts à présenter', Fichier Excel avec KPI dynamiques, Liste ciblée de 50 investisseurs sectoriels",
                differenciation: "Business plan complet vs modèles génériques, Pitch-decks professionnels vs présentations basiques",
                avantagesCompetitifs: "Complet, Professionnel, Ciblé",
                integrationEcosysteme: "Complémentaire aux autres programmes, Spécialisation financement",
                entonnoirNaturel: "Programme spécialisé pour financement",
                argumentsCommerciaux: "Obtenez un business plan qui convainc les investisseurs en 10 jours",
                urgence: "Business plans limités à 3 par mois",
                exemplesConcrets: "Entrepreneurs ayant obtenu des financements",
                casPratiques: "Modèle financier 3 ans, Pitch deck investisseurs, Stratégie financement",
                livrable: "Synthèse 2-3 pages, Fichier tableur de simulations, pitch-deck clients, pitch-deck investisseur, Stratégie financement",
                livrablesDetailles: "2 pitch decks 'prêts à présenter', Fichier Excel avec KPI dynamiques, Liste ciblée de 50 investisseurs sectoriels",
                supportsInclus: "Templates de pitch deck, Modèles Excel, Liste investisseurs",
                faq: "Q: Avez-vous besoin de mes données financières ? R: Oui, pour un business plan précis et crédible. Q: Les pitch-decks sont-ils personnalisés ? R: Oui, ils sont adaptés à votre projet et votre secteur",
                objectionsAnticipees: "Objection : 'Je peux faire ça moi-même' → Réponse : 'Un business plan professionnel fait la différence auprès des investisseurs'. Objection : 'C'est cher' → Réponse : 'Cela peut vous faire gagner des mois dans votre recherche de financement'",
                statut: "actif"
            },
            {
                nom: "Devenir Mentor en Afrique",
                slug: "devenir-mentor-afrique",
                sousTitre: "Programme pour accompagner des startups africaines",
                description: "Programme pour experts retraités/consultants seniors souhaitant monétiser leur réseau et savoir-faire en Afrique",
                conceptFondateur: "Problème : Comment monétiser mon réseau et savoir-faire en Afrique ? Solution : Programme de formation pour devenir mentor en Afrique",
                cible: "Experts retraités/consultants seniors",
                problemeResolu: "Comment monétiser mon réseau et savoir-faire en Afrique ?",
                niveauPriorite: 3,
                contenu: "Webinaire 1 : Écosystèmes startups Dakar/Casablanca, Webinaire 2 : Cultural intelligence (négociation Afrique), Webinaire 3 : Cas pratiques sectoriels, Webinaire 4 : Modèles de rémunération (€500-2k/mois)",
                processus: "Webinaire 1 : Écosystèmes startups, Webinaire 2 : Cultural intelligence, Webinaire 3 : Cas pratiques, Webinaire 4 : Modèles de rémunération",
                duree: "4 webinaires de 90 min",
                prix: "495 €",
                prixOriginal: null,
                garantie: "Satisfait ou remboursé 30 jours",
                conditionsPaiement: "Paiement unique",
                preuves: "Mentors ayant obtenu des contrats en Afrique",
                temoignages: "Experts ayant monétisé leur savoir-faire en Afrique",
                resultatsAttendus: "Certification 'Mentor Afrique 2024', Annuaire partenaires locaux, Template de contrat de mentorat",
                differenciation: "Spécialisation Afrique vs mentorat générique, Cultural intelligence vs approche occidentale",
                avantagesCompetitifs: "Spécialisé Afrique, Cultural intelligence, Réseau local",
                integrationEcosysteme: "Complémentaire aux autres programmes, Spécialisation Afrique",
                entonnoirNaturel: "Programme spécialisé pour mentorat Afrique",
                argumentsCommerciaux: "Monétisez votre savoir-faire en Afrique avec des rémunérations de €500-2k/mois",
                urgence: "Programme limité à 30 participants par session",
                exemplesConcrets: "Experts ayant obtenu des contrats de mentorat en Afrique",
                casPratiques: "Écosystèmes startups Dakar/Casablanca, Cultural intelligence, Modèles de rémunération",
                livrable: "Série de 4 webinaires de 90 mn",
                livrablesDetailles: "Certification 'Mentor Afrique 2024', Annuaire partenaires locaux, Template de contrat de mentorat",
                supportsInclus: "Templates de contrat, Annuaire partenaires, Certification",
                faq: "Q: Dois-je avoir de l'expérience en Afrique ? R: Non, nous vous formons à la cultural intelligence. Q: Les rémunérations sont-elles garanties ? R: Nous vous donnons les outils, c'est à vous de prospecter",
                objectionsAnticipees: "Objection : 'Je ne connais pas l'Afrique' → Réponse : 'Nous vous formons à la cultural intelligence'. Objection : 'Les rémunérations sont faibles' → Réponse : '€500-2k/mois pour un travail à distance'",
                statut: "actif"
            },
            {
                nom: "African Start-Up Co-Founder",
                slug: "african-startup-cofounder",
                sousTitre: "Intégration comme co-fondateur dans une startup africaine",
                description: "Programme pour entrepreneurs en reconversion totale, prêts à s'impliquer comme co-fondateur actif",
                conceptFondateur: "Problème : Je veux une aventure entrepreneuriale clé-en-main. Solution : Intégration comme co-fondateur dans une startup africaine",
                cible: "Entrepreneurs en reconversion totale, prêts à s'impliquer comme co-fondateur actif",
                problemeResolu: "Je veux une aventure entrepreneuriale clé-en-main",
                niveauPriorite: 3,
                contenu: "Phase 1 : Immersion Écosystème - Session 1 : Panorama startups africaines (secteurs porteurs), Session 2 : Atelier 'Où se situer ?' (passion/expertise vs opportunités). Phase 2 : Scouting Stratégique - Session 3 : Méthodologie de veille sectorielle, Session 4 : Identification de 5 startups 'fit'. Phase 3 : Matching & Rôle - Session 5 : Rencontres avec 3 startups présélectionnées, Session 6 : Pacte fondateurs (rôle + contribution). Phase 4 : Implémentation - Sessions 7-8 : Coaching opérationnel mensuel (stratégie + suivi)",
                processus: "Phase 1 : Immersion Écosystème, Phase 2 : Scouting Stratégique, Phase 3 : Matching & Rôle, Phase 4 : Implémentation",
                duree: "8 sessions sur 3 mois",
                prix: "2 495 €",
                prixOriginal: null,
                garantie: "Satisfait ou remboursé 30 jours",
                conditionsPaiement: "Paiement unique ou 3x",
                preuves: "Pierre, ex-DG : 'J'ai investi 20k€ pour 40% d'une startup logistique à Dakar. CA prévu : 500k€ en 2024'",
                temoignages: "Entrepreneurs ayant intégré des startups africaines comme co-fondateurs",
                resultatsAttendus: "Intégration comme co-fondateur dans une startup africaine, Coaching opérationnel mensuel",
                differenciation: "Intégration startup vs simple investissement, Coaching opérationnel vs conseil ponctuel",
                avantagesCompetitifs: "Intégration startup, Coaching opérationnel, Réseau africain",
                integrationEcosysteme: "Complémentaire aux autres programmes, Spécialisation Afrique",
                entonnoirNaturel: "Programme spécialisé pour co-fondation Afrique",
                argumentsCommerciaux: "Devenez co-fondateur d'une startup africaine en 3 mois",
                urgence: "Programme limité à 10 participants par session",
                exemplesConcrets: "Marc, 57 ans (ex-directeur logistique) : Immersion : Découverte du boom tech agro-alimentaire à Abidjan, Scouting : Identification de 'AgriConnect' (plateforme producteurs), Matching : Accord comme COO en charge de la supply chain, Implémentation : Mise en place d'un réseau de distribution en 12 semaines",
                casPratiques: "Cartographie des hubs tech (Dakar, Abidjan, Casablanca), Base de 15 startups 'fit' avec critères, Grille de compatibilité valeurs/compétences, Journal de bord personnalisé (objectifs 30/60/90j)",
                livrable: "Séances de coaching & webinaires, Matching projet, Pack installation, Contrats types",
                livrablesDetailles: "Carte interactive + PDF dynamique, Template Airtable, Questionnaire algorithmique, Template Notion",
                supportsInclus: "Templates de contrats, Base de données startups, Outils de suivi",
                faq: "Q: Dois-je investir de l'argent ? R: Cela dépend du projet, mais nous vous aidons à négocier les termes. Q: Les startups sont-elles fiables ? R: Nous sélectionnons rigoureusement les startups selon des critères stricts",
                objectionsAnticipees: "Objection : 'Je ne connais pas l'Afrique' → Réponse : 'Nous vous accompagnons dans l'immersion culturelle'. Objection : 'C'est risqué' → Réponse : 'Nous sélectionnons rigoureusement les startups'",
                statut: "actif"
            },
            {
                nom: "Caméléon Marchand",
                slug: "cameleon-marchand",
                sousTitre: "Accompagnement 6 mois : Transformation globale",
                description: "Accompagnement complet de 6 mois pour transformation globale de l'entreprise",
                conceptFondateur: "Problème : Besoin d'une transformation globale de l'entreprise. Solution : Accompagnement complet sur 6 mois",
                cible: "À définir",
                problemeResolu: "À définir",
                niveauPriorite: 1,
                contenu: "À définir",
                processus: "À définir",
                duree: "6 mois",
                prix: "7 495 €",
                prixOriginal: null,
                garantie: "Satisfait ou remboursé 30 jours",
                conditionsPaiement: "Paiement unique ou 3x",
                preuves: "À définir",
                temoignages: "À définir",
                resultatsAttendus: "À définir",
                differenciation: "À définir",
                avantagesCompetitifs: "À définir",
                integrationEcosysteme: "À définir",
                entonnoirNaturel: "À définir",
                argumentsCommerciaux: "À définir",
                urgence: "À définir",
                exemplesConcrets: "À définir",
                casPratiques: "À définir",
                livrable: "À définir",
                livrablesDetailles: "À définir",
                supportsInclus: "À définir",
                faq: "À définir",
                objectionsAnticipees: "À définir",
                statut: "actif"
            },
        ],
    });
    console.log("Produits insérés avec succès !");
}
main()
    .catch(e => {
    console.error(e);
    process.exit(1);
})
    .finally(async () => {
    await prisma.$disconnect();
});
